go_import_path: github.com/kevinburke/go-bindata

language: go

go:
  - '1.10.x'
  - '1.11.x'
  - master

script:
  - find . -type f | grep '/in/' | xargs chmod 420
  - make ci ; ls -al testdata/out
  - make bench

sudo: false
