go_import_path: github.com/kevinburke/go-bindata

language: go

os: linux
dist: trusty

before_script:
  - make install-travis

script:
  - make ci

sudo: required

cache:
  directories:
    - $HOME/.bzrepos
